services:
  app:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:2717/user-management
      - JWT_SECRET=your_secret_key_here  # Use a random string here
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    command: mongod --port 2717  # This forces MongoDB to run on 2717
    ports:
      - "2717:2717"              # Maps your computer's 2717 to container's 2717
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: